kiali/kiali.io

content/features/feature3.md, content/features/istio-configuration.md
- Create a video with subtitles demo-ing the IstioConfig page
- Adding a feature in kiali.io
Note: I used Feature3 for this as graph and services will come before.
Video link used: https://www.youtube.com/watch?v=f6V9CGoltv4
=> KIALI-1138 Showcase IstioConfig feature

.gitignore, config.toml, content/features/_index.md, content/features/feature1.md, content/features/feature2.md, content/features/istio-configuration.md, content/features/service-discovery.md, layouts/features/list.html, layouts/features/single.html, layouts/partials/header.html, static/css/kiali_style.css
=> KIALI-963 Showcase 'service list' / 'service detail' page

content/gettingstarted/index.md
=> KIALI-1423 Move Jaeger iFrame to external links - Update the website getting started with the new configuration

content/documentation/overview/index.adoc
Integrate feedbacks from @JStickler here https://github.com/kiali/kiali.io/pull/20#pullrequestreview-152624142
=> Doc overview: more feedbacks

content/gettingstarted/index.adoc
this doesn't directly address KIALI-1470 but it does document installing Kiali on a cluster where istio is installed.
=> update install instructions

layouts/index.html
=> Bring back image on start page.

content/gettingstarted/index.adoc
This section was recently added to the README in kiali/kialio repo.
=> kiali-1620 adding Additional notes section to Getting Started

layouts/index.html, static/css/kiali_style.css
=> Make features section on homepage clickable and navigate to features page

content/gettingstarted/index.adoc
Documents how to run Kiali with reduced permission in OpenShift.
=> KIALI-1659 Document running with reduced permissions

content/documentation/overview/index.adoc, static/css/kiali_style.css, static/files/validation_examples/001.yaml, static/files/validation_examples/002.yaml, static/files/validation_examples/101.yaml, static/files/validation_examples/102.yaml, static/files/validation_examples/103.yaml, static/files/validation_examples/104.yaml, static/files/validation_examples/105.yaml, static/files/validation_examples/106.yaml, static/files/validation_examples/107.yaml, static/files/validation_examples/108.yaml, static/files/validation_examples/109.yaml, static/files/validation_examples/110.yaml
List all the validations performed by kiali on Destination Rules and Virtual Services.
Validation message: Message that is shown in the ACEditor
Severity: error/warning
Description: broader description about the validation
Source: link to source code
Example: link to a yaml that triggers the validation explained
=> KIALI-1617 Add VS/DR validation list

layouts/index.html, static/css/kiali_style.css
=> update font size and color to blue

content/contribute/index.adoc
Add more text to make the page more inviting.
=> KIALI-1637 Augment contribute page

content/gettingstarted/index.adoc
pair this with https://github.com/kiali/kiali/pull/628
=> KIALI-1868 pass istio's namespace to the configmap

layouts/index.html
Match it to be the same as the more correct description that is in the source code readme.
=> Fix Kiali description

layouts/index.html
=> Add greek origin explanation

layouts/index.html, layouts/partials/header.html, static/css/kiali_style.css
=> Update font type and size for title, description and nav menu

layouts/index.html, static/css/kiali_style.css
=> Update style to the lower get started button

layouts/index.html, layouts/partials/header.html, static/css/kiali_style.css
=> Cleanup unused code,import fonts,apply Varela Round font

static/css/kiali_style.css
After the fix the link color is changed, but the size remains the same - which fixes the strange hover issue.
=> KIALI-2011 fix strange hover in documentation link

content/documentation/overview/index.adoc, static/files/validation_examples/201.yaml
Adding new Gateway validation (https://github.com/kiali/kiali/pull/672) to Validation list into overview section.
Here the output:
=> KIALI-2085 Add gateways multimatch validation into validations list

content/gettingstarted/index.adoc, layouts/documentation/glossary/list.html, layouts/documentation/list.html, layouts/features/list.html, static/css/kiali_style.css
check the code styling of "cluster-admin"
=> Fix code styling and remove redundant titles

static/css/kiali_style.css
=> Fix font type on documentation page and increase font size for all paragraphs

content/documentation/overview/index.adoc
Making DR multimatch validation consistent with the same one for Gateways.
https://github.com/kiali/kiali/pull/712
=> KIALI-2085 update multi match checker validation message for DR

static/css/kiali_style.css
fixing part of the styling issues documented in https://issues.jboss.org/browse/KIALI-2166
=> Fix mailing envelope color and got to top arrow background

static/css/kiali_style.css
remove the blue stripe (the screenshot is before the change)
=> Remove blue stripe above footer

config.toml, content/documentation/architecture.adoc, content/documentation/installation/index.adoc, content/documentation/prerequisites/index.adoc, content/gettingstarted/index.adoc, layouts/documentation/installation/single.html, layouts/partials/header.html
First view of installation docs
- [Istio docs](https://preliminary.istio.io/docs/tasks/telemetry/kiali/)
- [Maistra docs](https://maistra.io/docs/kiali/)
- [Github docs](https://github.com/kiali/kiali#building)
cc @jmazzitelli
=> KIALI-1470 Installation menus and docs

content/gettingstarted/index.adoc
see kiali-users mailing list thread: https://groups.google.com/forum/#!msg/kiali-users/GXJIFpXoiXM/JC0ud7qREgAJ
=> show the new URL to go to when deployed in minikube

static/css/kiali_style.css
=> KIALI-2174 Align the centers of social and group links

themes/canvas/static/js/functions.js
This fix the problem but I want to check where the theme is adding this class because in the top level this class is added automatically @abonas
=> KIALI-2186 website - third level menu opens to the right and overlaps main menu

layouts/partials/header.html, layouts/partials/menu.html, static/css/kiali_style.css, themes/canvas/static/js/functions.js
edit: Updated screenshot with latest changes
Also did a small refactor to remove repeated code.
=> KIALI-2208 Adds an arrow to menus with submenus

content/gettingstarted/index.adoc
reported in issue https://github.com/kiali/kiali/issues/812
can't pipe the script directly into bash because we need stdin for the prompts now (this was due to PR #https://github.com/kiali/kiali/pull/802 from JIRA 2294)
=> change docs since install script now needs stdin to prompt the user for credentials

content/gettingstarted/index.adoc
https://issues.jboss.org/browse/KIALI-1548
=> KIALI-1548 - document uninstall in the getting started page

content/documentation/overview/index.adoc
Updates certain validation texts and moves validation to its own subsection as we validate also in other places than just the Istio Config page. The current page structure is fixed to UI pages, but this is not an UI feature.
=> Update validation texts

content/documentation/overview/index.adoc
Documentation update after @amyroh improvement in https://github.com/kiali/kiali/pull/758
=> KIALI-2185 Allow VS to have empty weights in case actual weight sum is 100

content/documentation/overview/index.adoc, static/files/validation_examples/003.yaml
Updating validation documentation. DR were updated.
=> Update destination rule validations according current master state

content/documentation/overview/index.adoc, static/files/validation_examples/004.yaml
Adding documentation for https://github.com/kiali/kiali/pull/888
=> KIALI-2457 Add new validation on DestinationRules about meshwide mTLS

content/gettingstarted/index.adoc
Document the various login strategies that users can use in Kiali.
=> KIALI-2541 Document the login strategies

content/gettingstarted/index.adoc
=> KIALI-2783 update version compatibility

layouts/index.html
This just places an updated Kiali introductory video.
=> kiali-2861 Add new overview video

content/gettingstarted/index.adoc
Showing information for quick setup first, before more in-depth information. Trying to be more concise.
Added a couple of commands to edit Kiali config (CR)
JIRA: https://issues.jboss.org/browse/KIALI-2839
=> KIALI-2839 Rewrite getting started

layouts/index.html
See https://twitter.com/dgageot/status/1131855456308215808
=> Quote from David Gageot

layouts/index.html
- replace static top image with the bottom video
- remove bottom section
- add "configuration" to main blurb
- add "How is my mesh performing" to questions answered
- reformat index.html
=> KIALI-2954 Simplify landing page

content/contribute/index.adoc, layouts/partials/footer.html, layouts/partials/header.html
Add a link for Freenode IRC webclient pointing to Kiali room.
=> Add IRC link with freenode

static/css/kiali_style.css
Fix some styles title posts
cc @maryshak1996
=> Fix some styles blog posts

content/documentation/features/index.adoc, layouts/partials/footer.html, layouts/partials/header.html
Adding target blank to external links.
1. Increasing user session duration (not letting them easily leave our website)
2. Usability: easy for users to come back to kiali website.
=> Add target blank to all external links to increase user session time

README.adoc
=> Fix Hugo link

content/documentation/features/_index.adoc
=> Fixing features index page

content/documentation/validations/index.adoc, data/files/validation_examples/703.yaml
Updates the documentation to match updates from the PR kiali/kiali#1230
=> KIALI-3115 Service validation example and description improvements

content/documentation/getting-started/index.adoc
This PR add documentation for the `label_selector` feature discussed here: https://github.com/kiali/kiali/issues/1214
Fixes: https://github.com/kiali/kiali/issues/1214
=> Add documentation for label selector

content/documentation/getting-started/index.adoc
@jshaughn @pilhuhn just some getting started docs on the new LDAP feature.
For LDAP feature, see:
Issue: https://github.com/kiali/kiali/issues/1053
Server PR: https://github.com/kiali/kiali/pull/1323
UI PR: https://github.com/kiali/kiali-ui/pull/1335
=> issue 1053 - introduce the LDAP feature

content/documentation/getting-started/index.adoc
This builds on PR https://github.com/kiali/kiali.io/pull/156 and tweaks it to get it ready for publication.
=> issue 1053 support ldap

content/documentation/validations/index.adoc
Adding missing link to source code
=> Adding source code to virtualservice.singlehost validation

content/documentation/runtimes-monitoring/index.adoc
- New fields in CR: chartType, min/max, externalLinks
- Fix outdated prometheus config (#164)
Closes https://github.com/kiali/kiali/issues/1727
=> Update documentation on runtimes monitoring

content/documentation/getting-started/index.adoc
=> Fix broken link to Maistra setup docs

themes/kiali/layouts/_default/baseof.html, themes/kiali/layouts/partials/masthead.html, themes/kiali/static/css/kiali-home.css, themes/kiali/static/css/kiali.css
- Redirects to google with site:www.kiali.io
Preview:  https://deploy-preview-171--kiali-io-ci.netlify.com/
But the current code doesn't work very well from width 1050 to 1245.
Fixes kiali/kiali#1611 and replaces #157 
Also Closes kiali/kiali-design#142
=> Adds a search input

content/documentation/architecture.adoc, content/documentation/distributed-tracing/index.adoc, content/documentation/features/index.adoc, content/documentation/getting-started/index.adoc, content/documentation/glossary/networking/index.adoc, content/documentation/runtimes-monitoring/index.adoc, content/documentation/validations/index.adoc
I'm not quite ready to merge, but wanted to get a PR on the books.
=> Docs copyedit

themes/kiali/layouts/_default/baseof.html, themes/kiali/layouts/partials/masthead.html
Google allows you to create a custom search engine https://cse.google.es/cse/
That way, you have more options to customize the search page, for example, I added the Kiali logo out there.
The page ends up being more simple, i'm unsure if we should use it or keep the current one.
=> Experimenting with a google custom search engine

content/documentation/getting-started/index.adoc
Fixes https://github.com/kiali/kiali/issues/1766
=> Move Getting Started compatibility matrix to new Kiali Version Requirements section

content/documentation/architecture.adoc, content/documentation/runtimes-monitoring/index.adoc
@jshaughn are there any other places? These are the only ones I saw.
=> changes to env var docs

content/documentation/features/index.adoc
=> Add small mention for multi-cluster support

content/documentation/runtimes-monitoring/index.adoc
Closes https://github.com/kiali/kiali/issues/1820
=> Add Envoy dashboard documentation

content/contribute/index.adoc
Open form to get to know events with kiali involved. Better for us helping promoting and understanding community.
=> Adding events form into kiali.io/contribute

content/documentation/validations/index.adoc
Update needed because of https://github.com/kiali/kiali/pull/1988
Do not merge until https://github.com/kiali/kiali/pull/1988 is merged.
=> Updating doc to validation change in kiali/kiali#1988

content/documentation/getting-started/index.adoc
=> Add some documentation for the token login strategy

themes/kiali/layouts/partials/mastfoot.html, themes/kiali/static/css/kiali.css
Fix #188
also increase the font from 12 to 14 for license and privacy statement.
=> Add privacy statement link to footer

content/documentation/validations/index.adoc, data/files/validation_examples/106.yaml
Adding the related documentation to new validation here: https://github.com/kiali/kiali/pull/2108
Wait until that PR is merged please.
=> Adding VS validation: one route less than 100 weight

content/documentation/validations/index.adoc, data/files/validation_examples/005.yaml, data/files/validation_examples/101.yaml
Fixes https://github.com/kiali/kiali/issues/2127
=> Approaching small changes in kiali.io validations page

content/faq/graph/passthrough-traffic.adoc, themes/kiali/layouts/partials/home/features-section.html
- also: minor fix to feature card of landing page
Fixes https://github.com/kiali/kiali/issues/2130
=> Add Graph FAQ about PassthroughCluster

themes/kiali/layouts/partials/home/blog-latest-section.html
Latest blog posts sections wasn't updated automatically. It looks like the netifly engine was caching the html.
=> Blog posts not updated - fixing tests

content/faq/graph/service-rt.adoc
Fixes https://github.com/kiali/kiali/issues/2070
=> Add graph FAQ

content/documentation/extensions/index.adoc
=> Fix wrong image

content/documentation/validations/index.adoc, data/files/validation_examples/111.yaml
Adding documentation to new validation: https://github.com/kiali/kiali/pull/2206
=> Add subset duplicity in VR validation doc

content/documentation/validations/index.adoc, data/files/validation_examples/801.yaml, data/files/validation_examples/802.yaml
Adding documentation to new validation (https://github.com/kiali/kiali/pull/2224)
=> Add doc to AuthorizationPolicy validation - source.namespaces, operation.methods

content/documentation/validations/index.adoc, data/files/validation_examples/803.yaml
Documentantion of https://github.com/kiali/kiali/pull/2249
=> Documentation of AuthorizationPolicy#selector: no matching workloads

content/documentation/validations/index.adoc, data/files/validation_examples/009.yaml, data/files/validation_examples/301.yaml, data/files/validation_examples/402.yaml
Adding codes to each validation and sorting them by object type name alphabetically.
Backend part needed: https://github.com/kiali/kiali/pull/2275
Fixes: https://github.com/kiali/kiali/issues/1629
=> Add codes to each validation for better documentation and searchability

content/documentation/validations/index.adoc, data/files/validation_examples/804.yaml
Documentation of https://github.com/kiali/kiali/pull/2261
Merge first the backend part.
=> Add AuthPolicy validation: host not found

content/documentation/validations/index.adoc, data/files/validation_examples/901.yaml, data/files/validation_examples/902.yaml, data/files/validation_examples/903.yaml, data/files/validation_examples/904.yaml, data/files/validation_examples/905.yaml
Adding documentation to all present sidecar validations. It includes documentation for the latest PR opened for that: https://github.com/kiali/kiali/pull/2500#
List of validations:
https://github.com/kiali/kiali/pull/2500/files#diff-00df504feeb66372dea6b00a33164c66R202-R221
=> Add documentation for sidecars

content/documentation/validations/index.adoc, data/files/validation_examples/906.yaml
Adding documentation for https://github.com/kiali/kiali/pull/2544
=> Add doc about Global default sidecar

content/news/release-notes.adoc
- update structure a bit to handle multiple versions
- add 1.15.1
=> relnotes update 1.15.1

content/news/security-bulletins/KIALI-SECURITY-001.adoc
* Fix mitigation script
* Add detection script
* Fix wording in a sentence
* Add paragraph about the secondary security issue
=> Improve security bulletin 001

Makefile
To test:
```
CONTAINER_RUNTIME=podman make hugo-serve
```
=> Chore: Support podman for building and running the website

themes/kiali/layouts/partials/home/video-sprint-demo-section.html
Incorporate the latest sprint 37 demo video into Kiali.io sprint demo section.
=> Update the latest sprint demo 37 video to Latest sprint demo section.

Makefile, content/documentation/distributed-tracing/index.adoc, content/documentation/features/index.adoc, content/documentation/getting-started/index.adoc, content/documentation/glossary/concepts/index.adoc, content/documentation/glossary/networking/index.adoc, content/documentation/glossary/observability/index.adoc, content/documentation/validations/index.adoc, content/faq/distributed-tracing/certificate-unknown-authority.adoc, content/faq/distributed-tracing/no-tracing-about-modal.adoc, content/faq/general/how-do-i-access-kiai.adoc
fixes https://github.com/kiali/kiali/issues/2676
There is now `make muffet` which runs a tool called "muffet" that checks for broken links.
The tool isn't 100% accurate (some links are really OK, but it reports them as bad) but it is better than nothing.
=> Fix broken links, add muffet target to help detect broken links

themes/kiali/layouts/partials/home/about-section.html, themes/kiali/layouts/partials/home/hero-section.html, themes/kiali/layouts/partials/home/video-sprint-demo-section.html
Fixes https://github.com/kiali/kiali/issues/2689
@maltron @lucasponce , I tried a few suggestions from the issue comments and for me this is what looked best.  Note that this also tweaks the questions and the "about" blurb.   
As an aside this update the video section to include the most recent sprint demos.
=> Update website landing page

content/faq/general/what-are-minimum-rbac-privileges.adoc
=> Add FAQ entry for RBAC-enabled auth strategies

content/documentation/edge/faq/authentication/index.adoc, content/documentation/edge/faq/authentication/token-strategy.adoc
fixes: https://github.com/kiali/kiali/issues/2995
=> FAQ to explain how to get a token

content/documentation/edge/installation-guide/index.adoc, content/documentation/edge/quick-start/index.adoc
goes with:
* https://github.com/kiali/kiali/issues/195
* https://github.com/kiali/kiali-operator/pull/93
=> updates for helm

config.toml, content/contribute/index.adoc, content/documentation/edge/features/index.adoc, content/documentation/v1.22/features/index.adoc, themes/kiali/layouts/partials/mastfoot.html
I also includes:
- @jshaughn english-wide comments from a previous PR
- @lucasponce suggestion to put validations in the documentation menu
Fixes https://github.com/kiali/kiali/issues/2799
=> Adding Kiali Community Events into contribution page

config.toml
@xeviknal minor fix due unstable merge in our previous work
=> Remove duplicated validation entry

content/documentation/staging/validations/index.adoc, content/documentation/v1.22/validations/index.adoc
Relates to https://github.com/kiali/kiali/pull/3083
=> Updating selector(less) and workloadnotfound validations

content/documentation/staging/installation-guide/index.adoc, content/documentation/staging/quick-start/index.adoc
fixes https://github.com/kiali/kiali/issues/3094
The Quick Start and Installation Guide pages are the two things that were changed.
=> updates due to helm chart changes

content/documentation/staging/runtimes-monitoring/index.adoc
Fixes https://github.com/kiali/kiali/issues/3099 and https://github.com/kiali/kiali/issues/3037
=> Update custom dashbaords doc

content/documentation/staging/installation-guide/index.adoc
https://github.com/kiali/kiali/issues/3017
=> remove login and ldap auth strategies

content/documentation/staging/validations/index.adoc
Updating validation to https://github.com/kiali/kiali/issues/1471
=> Update validation with kiali-1471 issue

content/documentation/staging/quick-start/index.adoc, content/documentation/v1.22/quick-start/index.adoc
Fixes https://github.com/kiali/kiali/issues/3112
=> Supress no found warning removing kiali as istio sample

content/documentation/staging/faq/authentication/x-forwarded-port.adoc
see: https://github.com/kiali/kiali/issues/3111
=> add FAQ regarding X-Forwarded-Port when using OpenID

content/documentation/staging/faq/graph/mtls.adoc
Fixes https://github.com/kiali/kiali/issues/3152
=> https://github.com/kiali/kiali/issues/3152

themes/kiali/layouts/partials/home/video-getting-started-section.html, themes/kiali/layouts/partials/home/video-latest-section.html
Add new video content to getting started and latest videos sections.
- Helm chart install into Istio 1.7.x
- Enable Istio Auto injection from Kiali
=> Add new video content to getting started and latest videos sections.

themes/kiali/layouts/partials/home/video-latest-section.html
Add new logging enhancements video to kiali.io
=> Add new logging enhancements video.

content/documentation/staging/installation-guide/index.adoc, content/news/release-notes.adoc
- add release notes for 1.23
- update version compatibility chart given Istio release
- fix error in older deprecation notice
=> Release notes v1.23

themes/kiali/static/css/kiali-home.css, themes/kiali/static/css/kiali.css
A fix to my last PR that fixes the misalignment at some resolutions. I didn't realize that some resolutions are fixed pixels and some (>1500) are 15% padding.
=> [Fix] video alignment issues with other sections at certain resolutions.

content/documentation/staging/configuration/authentication/openid.adoc
RelatedBack-end PR is https://github.com/kiali/kiali/pull/3215
Related issue is kiali/kiali#3088
=> Add documentation related to the OpenId "autorization code" support

content/documentation/v1.24/features/index.adoc
Hello,
As said in title: fixing some typos on features page
Didier
=> fixing some typos on features page

content/documentation/v1.24/faq/graph/external-https-as-tcp.adoc, content/documentation/v1.24/faq/graph/graph-badly-laid-out.adoc
Hi,
As per titles: fix somes typos in FAQ
Didier
=> fix somes typos in FAQ

content/documentation/staging/installation-guide/index.adoc
This was fixed in the v1.24 docs via this PR https://github.com/kiali/kiali.io/pull/308/files but we also need to make the change in staging so we don't lose it.
=> Specify type for deletion [staging]

content/news/release-notes.adoc, themes/kiali/layouts/partials/home/video-sprint-demo-section.html
- Add sprint 45 sprint demo
- update sprint demo titles with associated version
=> - Add relnotes v1.24

content/documentation/staging/faq/general/psp-pod.adoc
Closes https://github.com/kiali/kiali/issues/3297
=> https://github.com/kiali/kiali/issues/3297

content/documentation/staging/validations/index.adoc, data/files/validation_examples/201.yaml
requires https://github.com/kiali/kiali/pull/3296
=> Adapting KIA0301 to consider multiple ingress gws

content/documentation/staging/installation-guide/index.adoc, content/documentation/v1.25/installation-guide/index.adoc
Documentation followup for https://github.com/kiali/kiali/pull/3383.
=> Add simple documentation for web_fqdn and web_port

content/documentation/staging/configuration/authentication/openid.adoc, content/documentation/v1.28/configuration/authentication/openid.adoc
Related to https://github.com/kiali/kiali/pull/3495.
=> Add documentation to using http(s) proxy for openid

content/documentation/staging/faq/graph/graph-badly-laid-out.adoc
Happy to rework any other verbiage while I'm here, but this seemed to be the least invasive way of editing this particular paragraph.
=> docs: Tidy up some of the English in Badly Laid Out Graph FAQ

content/documentation/staging/configuration/authentication/_index.adoc, content/documentation/staging/configuration/authentication/header.adoc
for https://github.com/kiali/kiali/issues/3207
=> added docs for header auth strategy

content/documentation/staging/faq/general/google-cloud-private-cluster.adoc, content/documentation/staging/installation-guide/index.adoc, content/documentation/v1.25/faq/general/google-cloud-private-cluster.adoc, content/documentation/v1.25/installation-guide/index.adoc, content/documentation/v1.26/faq/general/google-cloud-private-cluster.adoc, content/documentation/v1.26/installation-guide/index.adoc, content/documentation/v1.27/faq/general/google-cloud-private-cluster.adoc, content/documentation/v1.27/installation-guide/index.adoc, content/documentation/v1.28/faq/general/google-cloud-private-cluster.adoc, content/documentation/v1.28/installation-guide/index.adoc, content/documentation/v1.29/faq/general/google-cloud-private-cluster.adoc, content/documentation/v1.29/installation-guide/index.adoc
related to https://github.com/kiali/kiali/issues/3494
Pretty much based on https://istio.io/latest/docs/setup/platform-setup/gke/
=> Adding GKE private cluster requirement

content/news/release-notes.adoc, scripts/relnotes.py
Also, small script update for Python3 compatibility.
=> Release Notes v1.31.0

content/documentation/staging/faq/graph/mtls.adoc, content/documentation/staging/features/index.adoc
Updating doc according to changes in https://github.com/kiali/kiali-ui/pull/2106
needs https://github.com/kiali/kiali-ui/pull/2106
=> mTLS: Remove references to broken locks when strict mtls

content/documentation/v1.32/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.32/faq/general/how-do-i-access-kiai.adoc, content/documentation/v1.32/quick-start/index.adoc, themes/kiali/layouts/partials/mastfoot.html
Fixes https://github.com/kiali/kiali/issues/3834
=> Add Istio slack channel to contact spots

content/documentation/v1.32/faq/graph/prometheus.adoc
Fixes https://github.com/kiali/kiali/issues/3843
=> Improve prometheus FAQ entry

content/documentation/staging/faq/installation/operator-configuration.adoc
fixes: https://github.com/kiali/kiali/issues/3884
=> Document how to configure the operator at runtime

content/documentation/staging/faq/istio-component-status/component-unreachable.adoc
requires https://github.com/kiali/kiali/pull/3849
=> Adding new setting for overriding component url for health check

content/documentation/v1.33/configuration/authentication/openid.adoc
Replicating changes from PR #362 to v1.33 to make
it available to current/latest docs.
=> GKE doc manual pick

themes/kiali/layouts/partials/home/about-section.html
Fixes some small grammar issues in About Kiali section.
=> Change wording in About section

content/documentation/staging/architecture.adoc, content/documentation/staging/tutorial/04-observe/01-enable-sidecars-for-all-namespaces.adoc, content/documentation/v1.12/architecture.adoc, content/documentation/v1.17/architecture.adoc, content/documentation/v1.18/architecture.adoc, content/documentation/v1.19/architecture.adoc, content/documentation/v1.20/architecture.adoc, content/documentation/v1.21/architecture.adoc, content/documentation/v1.22/architecture.adoc, content/documentation/v1.23/architecture.adoc, content/documentation/v1.24/architecture.adoc, content/documentation/v1.25/architecture.adoc, content/documentation/v1.26/architecture.adoc, content/documentation/v1.27/architecture.adoc, content/documentation/v1.28/architecture.adoc, content/documentation/v1.28/tutorial/04-observe/01-enable-sidecars-for-all-namespaces.adoc, content/documentation/v1.29/architecture.adoc, content/documentation/v1.29/tutorial/04-observe/01-enable-sidecars-for-all-namespaces.adoc, content/documentation/v1.30/architecture.adoc, content/documentation/v1.30/tutorial/04-observe/01-enable-sidecars-for-all-namespaces.adoc, content/documentation/v1.31/architecture.adoc, content/documentation/v1.31/tutorial/04-observe/01-enable-sidecars-for-all-namespaces.adoc, content/documentation/v1.32/architecture.adoc, content/documentation/v1.32/tutorial/04-observe/01-enable-sidecars-for-all-namespaces.adoc, content/documentation/v1.33/architecture.adoc, content/documentation/v1.33/tutorial/04-observe/01-enable-sidecars-for-all-namespaces.adoc, content/documentation/v1.34/architecture.adoc, content/documentation/v1.34/tutorial/04-observe/01-enable-sidecars-for-all-namespaces.adoc
Fixes https://github.com/kiali/kiali/issues/4029
=> Fix broken links

content/documentation/staging/installation-guide/index.adoc
To review: https://deploy-preview-377--kiali.netlify.app/documentation/staging/installation-guide/#_helm_chart
=> add hint about helm chart values for the CR

content/contribute/index.adoc, content/documentation/staging/faq/general/how-can-i-get-in-touch.adoc, content/documentation/staging/faq/graph/graph-badly-laid-out.adoc, content/documentation/v1.12/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.17/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.18/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.19/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.20/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.21/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.22/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.23/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.24/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.25/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.26/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.27/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.28/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.29/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.30/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.31/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.32/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.33/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.34/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.35/faq/general/how-can-i-get-in-touch.adoc, content/documentation/v1.35/faq/graph/graph-badly-laid-out.adoc, themes/kiali/layouts/partials/mastfoot.html
- IRC moving from freenode to libera
- kiali mailing lists retired in favor of slack
=> Update contact points given:

content/documentation/staging/configuration/authentication/openid.adoc
=> Instructions to configure a trusted CA for OpenID requests

content/documentation/staging/runtimes-monitoring/index.adoc, content/documentation/v1.36/runtimes-monitoring/index.adoc, content/documentation/v1.37/runtimes-monitoring/index.adoc
Fixes https://github.com/kiali/kiali/issues/4182
=> Update custom dashboards annotations

content/documentation/staging/faq/installation/sidecar-injection.adoc
fixes: https://github.com/kiali/kiali/issues/4258
netlify link: https://deploy-preview-397--kiali.netlify.app/documentation/staging/faq/#sidecar-injection
see also: https://github.com/kiali/kiali-operator/pull/388
=> document how to add a sidecar to kiali

content/documentation/staging/faq/installation/sidecar-injection.adoc
netlify link: https://deploy-preview-398--kiali.netlify.app/documentation/staging/faq/#sidecar-injection
=> explain how to inject sidecar in kiali on Openshift

themes/kiali/layouts/partials/mastfoot.html, themes/kiali/layouts/partials/masthead.html, themes/kiali/static/css/kiali.css
Fixes https://github.com/kiali/kiali/issues/3835
Footer:
- re-order icons by importance
- add spacing between and below
- add tooltips
- 
Header
- a couple of tweaks for better rendering of the search form.
=> [kiali.io] Improve social icons on footer and add some to header
