kiali/kiali.io

- layouts/partials/header.html
Accessing to kiali.io in https triggers an error of insecure request because of the font import.
Changing this import to https makes kiali works for both http and https since it is not a problem (the opposite) to make request to https from a non-secure webpages.
> Use always https for font import

- content/gettingstarted/index.md
Updates the doc to indicate that we now support Istio 1.0
Removed redundant steps to first log in as a cluster-admin and then to grant another user the cluster admin permissions and then log in as that new user.
> KIALI-1358: Update docs for v0.6.0

- content/documentation/known_issues/index.adoc
the documentation page (https://www.kiali.io/documentation/) has a bad link to known issues (the URL has "known issues" - missing the underscore "known_issues").
This fixes it.
I do not know how to get the link text to show a space but the actual link to use underscore, so this fix shows underscore in the link text as well as in the URL.
> fix the known issues link found on the documentation page

- content/documentation/known_issues/index.adoc
- content/documentation/prerequisites/index.adoc
Adds a note about what browsers we support.
Our UI is using patternfly and this is where I am getting the recommended browser list from: https://www.patternfly.org/get-started/frequently-asked-questions/#support
It also adds a note into our 'known issues' section that IE11 is not supported and to see the docs for a list of supported browsers.
> KIALI-1574 Note which browsers are supported

- content/gettingstarted/index.adoc
Preparing kiali.io for v0.9.0 release. I have updated version on the installation examples, just to be updated.
This PR also is meant to update the API documentation. I am waiting now for https://github.com/kiali/kiali/pull/569.
> KIALI-1754 Updating installation examples to v0.9.0 version

- Makefile
- README.adoc
The current kiali.io instructions for how to get it up and running is broken.
The old way of building Hugo from source doesn't seem to work and more and it makes things a lot more complicated.
Using Hugo in a docker container seemed like a good idea, but then it doesn't work well with building it in Travis.
This update makes things a lot more simple and just asks users to install Hugo manually and have the 'hugo' binary in the path.
> KIALI-1965 Update instructions to install Hugo manually

- Makefile
- README.adoc
- hugo/Dockerfile
Now people have the option to just run "make hugo-serve" rather than install hugo/asciidoc.
For now, you have to build the docker container first "make hugo-docker" but if this PR is good, we can publish our hugo+asciidoc image to doc hub and people won't even need to build it.
NOTE: This does NOT affect the previous way things work. The Makefile still has the targets it had before and you can still install hugo/asciidoctor locally. So it still works the way it did originally. This only adds the optional feature of letting someone run the docker image if they don't want to install those tools locally.
> support users who do not have hugo+asciidoc installed on their box.

- layouts/index.html
Homepage video is from version 0.3. We are at 0.14. I guess it would be great to replace it for a fresher one. I just found this vid from @pilhuhn (from mid october).
This is a wdyt PR, so wdyt?
> Update outdated demo video on homepage

- content/documentation/overview/index.adoc
- static/files/validation_examples/401.yaml
Adding documentation of the validation introduced into kiali/kiali-2093.
This PR is in DNM until  kiali/kiali-2093 is merged.
> Adding documentation for MeshPolicy validation in KIALI-2093

- content/documentation/runtimes-monitoring/index.adoc
Also adding references to new dashboards (related to labelling issue, see https://github.com/kiali/kiali/pull/931 )
> KIALI-2480 add dashboard documentation about labelling

- layouts/partials/header.html
- static/css/kiali_style.css
Remove the dark class we keep the background style of the dropdown in white.
I am worried about this. 
The javascript file [themes/canvas/static/js/functions.js](https://github.com/kiali/kiali.io/blob/master/themes/canvas/static/js/functions.js) of the canvas theme applied the style [dark.css](https://github.com/kiali/kiali.io/blob/master/themes/canvas/static/css/dark.css) when the user scroll down, this file make all the magic adding and removing classes. 
Right now we are overwriting the css rules in the [kiali_style.css](https://github.com/kiali/kiali.io/blob/master/static/css/kiali_style.css) file in some cases with **!important**
We are changing  practically the canvas theme and I think that we should create a new theme for Kiali (Jaeger website has their own theme) with the UX …
> KIALI-2142 Update styling on website drop down menu of Documentation section

- content/gettingstarted/index.adoc
The service account name was updated a while ago to match what is being used in upstream Istio. But the docs for running with reduced permissions was not updated at that time.
> KIALI-2358 Update doc to include updated service account name

- config.toml
- layouts/index.html
- layouts/partials/home/articles.html
- layouts/partials/home/features.html
- layouts/partials/home/introduction.html
- static/css/kiali_style.css
I saw how in jaeger they show the last posts of their blog in their website. They have a link in the main menu to the blog and we only have the "medium" icon, What do you think about to show the lasts posts like them in the website @abonas @theute ? Here is the PoC
- Configuration of the lasts posts in the config.toml
- Structure the partials
> More visibility to posts in Kiali website

- content/documentation/getting-started/index.adoc
Fixing small error type in Uninstall section:
> oc delete namespace kiali-operator
instead of 
> oc delete namespace -n kiali-operator
> Small command mistake in uninstall section

- content/documentation/getting-started/index.adoc
- attempts to clarify installation and upgrade options by emphasizing differences between packaged Kiali
installation (Istio/Maistra) and Latest Kiali installation (Operator).
- renames the Latest install options from Default,Demo/Dev,Operator-Only to
Quick,Development,Advanced.
- attempts to clarify the difference between kiali operator and kiali
- adds a bit more to the uninstall-hang issue info
- moves Uninstall section up and also makes distinct uninstall of just kiali vs
a complete wipe of everything
- remove giant title on os console screenshot
> This revision of Getting Started:

- scripts/template.hbs
- static/css/kiali_style.css
- themes/canvas/static/style.css
- Increase the dev API menu width to prevent cropping (at least for today's entries)
- Increase the overall width of usable space (to 90%) for all of the pages using the
current theme.
Note: to do a test build of this you need to pull the branch and then:
> make build
> make serve
Before:
After:
> KIALI-3060 Reduce developer API cropping

- content/contribute/index.adoc
* GitHub has replaced JIRA. Update the section about how to report
issues.
* Extend section about getting in contact.
Closes kiali/kiali#1548
> Updates to contributing page

- README.adoc
- themes/kiali/layouts/partials/mastfoot.html
- themes/kiali/static/css/kiali.css
The Open source plan of Netlify requires to place a badge in the
website. This PR is adding the badge at the footer.
Also, a deploy badge is added in README.md to see the result of the last
build and have access to the logs.
> Add Netlify badges

- content/contribute/index.adoc
- content/documentation/architecture.adoc
- content/documentation/distributed-tracing/index.adoc
- content/documentation/features/index.adoc
- content/documentation/getting-started/index.adoc
- content/documentation/glossary/concepts/index.adoc
- content/documentation/glossary/networking/index.adoc
- content/documentation/glossary/observability/index.adoc
- content/documentation/runtimes-monitoring/index.adoc
- content/documentation/validations/index.adoc
- content/faq/general/how-can-i-get-in-touch.adoc
- content/faq/general/how-contribute.adoc
- themes/kiali/layouts/faq/single.html
Adding anchor links to sections. Ease the job of sharing only one section of the page.
The current scenario for me is for sharing the events form.
Closes: kiali/kiali#1526
> Add anchors to each section title, for better traffic forwarding

- config.toml
Google wants us to have a sitemap.xml with absolute urls.
> Sitemap.xml fix: need baseURL set to be compliant

- themes/kiali/layouts/faq/list.html
The introduction of a baseURL made the staging environment of netlify have problems in the FAQ page. Links where absolute so it was pointing to production environment.
https://github.com/kiali/kiali.io/pull/198#issuecomment-583170747
This branch fixes that making hugo serve relative path instead.
> Relative Link into FAQ page: baseURL introduction degraded dev experience on FAQ

- content/documentation/validations/index.adoc
There was a package rename in the validations that made broke some links to source code.
This fixes all of them.
> Revisiting outbound links

- content/documentation/getting-started/index.adoc
For development builds of Kiali this PR adds two things:
1. Also update the Kiali Operator
2. Developers probably want the latest master and not last released (which may already be out of date with current master and incompatible).
> For Kiali dev install use the latest master version of Kiali and operator

- config.toml
- content/news/_index.adoc
- content/news/release-notes.adoc
- content/news/security-bulletins/KIALI-SECURITY-001.adoc
- content/news/security-bulletins/_index.adoc
- themes/kiali/layouts/_default/list.html.html
Closes https://github.com/kiali/kiali/issues/2536.
Release notes come from epics/epic subtasks on Sprint 36, while security bulletin is just an example.
What is still broken (and will be fixed in other PRs):
* Hovering the menu item opens the dropdown menu in an incorrect
position:
* Tables do not work on our layout, breaking horribly for some reason. Need more work to investigate on this.
News page:
Release notes:
Security bulletins list:
Security bulletin page:
> Add pages for Release Notes and Security Bulletins

- config.toml
- content/contribute/index.adoc
- content/documentation/features/index.adoc
- content/documentation/getting-started/index.adoc
- themes/kiali/static/css/kiali.css
- CSS fix to correct positioning of the News dropdown
- let config.toml be the sole definer of the main menu by removing menu.main decls in explicit pages.  And simplify the weight numbering.
> Fix News menu dropdown

- themes/kiali/layouts/index.html.html
- themes/kiali/layouts/partials/home/hero-section.html
- themes/kiali/layouts/partials/home/video-latest-section.html
- themes/kiali/layouts/partials/home/video-sprint-demo-section.html
- themes/kiali/static/css/kiali-home.css
This uses inlined videos to show thumbnails of the videos and increase awareness of the use of Kiali.
It added two sections to Kiali.io:
1. Latest Videos
2. Sprint Demo Videos
This brings awareness to Kiali videos from both a Sprint Demo perspective and quickly learning a new feature.
New:
> Add a latest videos and sprint demos section to Kiali.io. 

- content/documentation/getting-started/index.adoc
- static/_redirects
fixes: https://github.com/kiali/kiali/issues/2654
fixes: https://github.com/kiali/kiali/issues/2655
This creates a 301 redirect so getLatestKialiOperator redirects to the deploy script in the kiali-operator github repo.
The documentation also is changed to refer to this new kiali.io (as opposed to git.io) link.
> getLatestKialiOperator redirect

- config.toml
- content/documentation/features/index.adoc
- content/documentation/runtimes-monitoring/index.adoc
- Renaming "Runtimes monitoring" to "Custom dashboards". Note that the pod annotation "kiali.io/runtimes" being changed to "kiali.io/dashboards" doesn't require code change: "kiali.io/dashboards" was already recognized before for the same purpose, but was undocumented.
- Document the requirement to have a "namespace" label on metrics
- Improve documentation on external links, include an example
- Mark "metricName" field deprecated, introduce new "metrics" field (as list)
- Few other minor clarifications
Fixes https://github.com/kiali/kiali/issues/2717, https://github.com/kiali/kiali/issues/2716 and https://github.com/kiali/kiali/issues/2701
> Several updates on custom dashboards

- scripts/backfill-tags.sh
- sync-tags.sh
Part of https://github.com/kiali/kiali/issues/2181.
This is a script that I need to run on the repository to generate the tags for older versions that we released, so I can use those tags to generate the versioned documentation.
After this is merged, I am going to run it on the repo and push the tags generated by it.
> Add script to fill all versioned git tags retroactively

- scripts/relnotes.py
First version generates only .0 release notes for a sprint release.
> Add a simple release notes generator using github api

- content/documentation/validations/index.adoc
- data/files/validation_examples/004.yaml
- data/files/validation_examples/008.yaml
- data/files/validation_examples/112.yaml
- data/files/validation_examples/301.yaml
- data/files/validation_examples/401.yaml
This PR approach two problems:
- Adding a new validation added in kiali/kiali#2794
- Rewrite and make sure that Policy-related validations are aligned with the PeerAuthn scenarios.
Needs  kiali/kiali#2794 to be merged
> Validations: add gateways format validation + rewritting policy validations

- content/documentation/validations/index.adoc
- data/files/validation_examples/302.yaml
- data/files/validation_examples/303.yaml
- data/files/validation_examples/304.yaml
Documentation of https://github.com/kiali/kiali/pull/2808
Needs backend part first.
> Adding MultiMatch/NoWorkloadFound validations to PeerAuthentications

- config.toml
By our configuration, all links are not relative but have the `kiali.io` root to them. This breaks staging deploys on netlify, as it points all links to production.
This does not affect:
* Copying links, the browser adds the root automatically.
* SEO, the relative links are counted the same.
> Use relative links to fix staging deploys

- content/documentation/archive/v1.12/getting-started/index.adoc
Fixed a minor typo : cluser to cluster in the documenation for Kiali RBAC
> chore(doc): fix typo

- content/documentation/getting-started/index.adoc
Part of kiali/kiali#2863 and kiali/kiali#2862.
Fixes kiali/kiali#2864.
> Add deprecation for "login" and "ldap" auth strategies; add documentation for "openid" strategy

- Makefile
This does the same as the operator CI Makefile, which contains a version that is updated by the release scripts.
> Add version to Makefile to conform to CI

- content/documentation/edge/validations/index.adoc
- content/documentation/v1.18/validations/index.adoc
- content/documentation/v1.19/validations/index.adoc
- data/files/validation_examples/305.yaml
- data/files/validation_examples/306.yaml
This PR two different things:
1. Lost validations during the migration to versioned docs: https://github.com/kiali/kiali.io/pull/240 , https://github.com/kiali/kiali.io/pull/235
2. New validations for https://github.com/kiali/kiali/pull/2850
> Update validations: Restoring lost ones + PeerAuthentications

- themes/kiali/layouts/index.html.html
- themes/kiali/layouts/partials/home/blog-latest-section.html
- themes/kiali/layouts/partials/home/events-latest-section.html
I've added a new section in our home page where events related to kiali are going to be listed.
The source of this is a Google SpreadSheets which only the kiali team can edit. This spreadsheet is similar to the resulting one from the public form available to the community: bit.ly/3egKs58
If this PR gets merged, I'll invite to all of the kiali team to that spreadsheet.
wdyt?
> Add kiali events on our home page

- themes/kiali/layouts/_default/list.html.html
This fixes an error on the layout that was filtering the index page when accessing it through the `latest` endpoint (accessing the version directly was ok, though).
This happens because Hugo does not know about symlinks and can not expand the url, unfortunately.
Before:
After:
> Fix filtering on listing page

- content/documentation/edge/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.10/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.11/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.12/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.13/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.14/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.15/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.16/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.17/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.18/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.19/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.5/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.6/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.7/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.8/faq/general/how-do-i-access-kiai.adoc
- content/documentation/v1.9/faq/general/how-do-i-access-kiai.adoc
- themes/kiali/layouts/faq/list.html
Closes https://github.com/kiali/kiali/issues/2994
So, at it turns out, our faq being (barely) functional before the versioning is just an unlikely alignment between hugo and the content  we had at the time. As soon as things get more complicated it breaks down horribly.
This should fix some of the problems, at least the ones we've encountered until now.
* Fix header links.
* Add the content directly to the page.
* Fix some of the links on old versions of the "getting-started" page.
Proof of life:
> Fix FAQ Links

- themes/kiali/layouts/faq/list.html
So, continuing on the work of hugo making things that should be simple not so simple, this commit brings back a table of contents, explicit on the layout.
This commit also cleans up the generated html a little by not using a list for the page contents.
It should look like this now:
> Force presence of a table of contents on faq pages

- Makefile
When doing the manual release for v1.20, I forgot to change the version in the Makefile to the correct one (the next one going to be released).
This PR fixes that.
> Point Makefile to correct version

- config.toml
Minor change to have a better clean menu.
Validations is an important entry in the menu and it deserves to be in the main menu to be less "hidden".
> Move validations to main_doc menu

- content/documentation/staging/quick-start/index.adoc
- content/documentation/v1.22/quick-start/index.adoc
zsh has different syntax for brackets on command lines, but since accessible namespaces is ** by default, just don't specify it. This makes the documented command the same on all platforms.
fixes: https://github.com/kiali/kiali/issues/3108
> remove accessible_namespaces from documented helm command

- themes/kiali/layouts/index.html.html
- themes/kiali/layouts/partials/home/video-getting-started-section.html
This adds a 'Getting Started Videos' so that the 'Latest videos' section can be just that the latest cool videos; but that we have a highly visible place for beginners to see how to use Kiali.
fixes: https://github.com/kiali/kiali/issues/3117
> Add a 'Getting Started Video' section 

- config.toml
- content/documentation/staging/configuration/_index.adoc
- content/documentation/staging/configuration/authentication/_index.adoc
- content/documentation/staging/configuration/authentication/anonymous.adoc
- content/documentation/staging/configuration/authentication/openid.adoc
- content/documentation/staging/configuration/authentication/openshift.adoc
- content/documentation/staging/configuration/authentication/token.adoc
- content/documentation/staging/configuration/rbac.adoc
- content/documentation/staging/installation-guide/index.adoc
- content/documentation/staging/quick-start/index.adoc
This is adding documentation for kiali/kiali#3142. However, since the authentication-related docs are now quite large, this is also re-organizing that content.
All authentication-related content was mostly placed in the installation guide, which is already quite large and somewhat confusing. So, authentication-related content was extracted from the installation guide and placed on it's own pages, hoping is clearer.
RBAC documentation is also extracted and unified to it's own pages. It is reworked because it was scattered and some parts of it were quite outdated.
Related to kiali/kiali#3042
Fixes kiali/kiali#2771
> Add docs for OpenID API proxy and general reorg of auth docs

- scripts/build-archive.sh
Because `edge` was renamed to `staging`.
> Fix build-archive script

- content/documentation/v1.24/installation-guide/index.adoc
```
➜ kubectl delete monitoringdashboards.monitoring.kiali.io
error: resource(s) were provided, but no name, label selector, or --all flag specified
➜ kubectl delete crd monitoringdashboards.monitoring.kiali.io
customresourcedefinition.apiextensions.k8s.io "monitoringdashboards.monitoring.kiali.io" deleted
➜ kubectl delete kialis.kiali.io
error: resource(s) were provided, but no name, label selector, or --all flag specified
➜ kubectl delete crd kialis.kiali.io
customresourcedefinition.apiextensions.k8s.io "kialis.kiali.io" deleted
```
> Specify type for deletion

- content/documentation/staging/configuration/authentication/openid.adoc
There is a paragraph in the "Setup" section saying that users should
create a new app/client on it's OIDC Server. This is wrong: they should
re-use the existent one created when configuring OIDC integration with
the Kubernetes cluster.
This is fixing that paragraph.
Also, other small improvements.
Related to kiali/kiali#3294
> OpenID doc setup amendment

- content/documentation/staging/faq/graph/index.adoc
- content/documentation/staging/faq/installation/cluster-role-creator.adoc
- content/documentation/staging/faq/installation/index.adoc
Add FAQ to educate people about the error that will occur if you use clusterRoleCreator=false and accessible_namespaces of **.
We will need this since we needed to rip out the human-readable error due to https://github.com/kiali/kiali-operator/pull/167
Note this introduces a new section of the FAQ named "Installation"
> add new FAQ section named "Installation" with first entry

- content/documentation/staging/configuration/authentication/openid.adoc
Adding documentation to configure Kiali with OpenID authentication and
RBAC disabled.
Related kiali/kiali#3084
> Documentation for OpenID with RBAC disabled

- content/documentation/staging/glossary/concepts/index.adoc
- content/documentation/staging/glossary/observability/index.adoc
- content/documentation/staging/installation-guide/index.adoc
- content/documentation/v1.26/glossary/concepts/index.adoc
- content/documentation/v1.26/glossary/observability/index.adoc
- content/documentation/v1.26/installation-guide/index.adoc
- content/news/release-notes.adoc
- remove mixer references
- add feature that was missed from the 1.26 relnotes
- update compatibility chart
> Doc updates for 1.26

- themes/kiali/layouts/index.html.html
- themes/kiali/layouts/partials/home/video-sprint-demo-section.html
- themes/kiali/static/css/kiali-home.css
Goal: Automatically update the sprint-videos section in kiali.io.
If we upload the sprint demo on youtube before the automatic release deploy is performed (Friday EOD), then Kiali.io will automatically fetch and build with that video.
As it is right now, we should have to manually change the page to add the video. This section is currently updated and shows some gaps between videos.
Pre-requisite before merge this video:
1) Add the latests sprint demo videos into the [Sprint demos playlist](https://www.youtube.com/playlist?list=PLgwrCYrAkQYOHIeGukEZUmNRGbqI9uwpi). The changes proposed here are displaying only videos in that playlist.
2) Have an agreement that we will add upcoming videos into that playlist.
3) Have an agreement to name the videos on Youtube in standardized way making sure …
> Automatic fetching sprint videos from youtube playilist

- content/documentation/staging/configuration/rbac.adoc
Doc says that minimum privileges required to login will turn kiali
unusable. This is not totally true, as pages that work purely from
metrics will work OK. So, changing that paragraph to be more accurate.
Fixes kiali/kiali#3575
> Fix minimum privileges docs

- Makefile
- README.adoc
- config.toml
- Add a new make target (serve-latest) to speed up site generation by
skipping all archived versions
- Add ":z" flag for selinux compatibility on volume mounts
> Faster site generation + selinux compat

- content/documentation/staging/installation-guide/index.adoc
fixes: https://github.com/kiali/kiali/issues/3943
> Make it clear that accessible_namespaces must not share namespaces across kiali instances

- content/documentation/staging/installation-guide/index.adoc
Adds an `Upgrade` section to the install guide that gives instructions for updating Kiali during an Istio canary upgrade and for upgrading Kiali itself. Also adds information in the install section for using the `kiali-server` helm chart to install Kiali without the operator.
Relates to https://github.com/kiali/kiali/issues/2884
> Add upgrade section and install docs on kiali-server chart

- content/documentation/staging/installation-guide/index.adoc
Add a new section to talk about installing multiple instances of Kiali Server. Also made some minor changes elsewhere for consistency.
The netlify link to see the changes is this: https://deploy-preview-374--kiali.netlify.app/documentation/staging/installation-guide/#_installing_multiple_instances_of_kiali
These are docs for:
* https://github.com/kiali/kiali/issues/3920
* https://github.com/kiali/kiali-operator/pull/313
> updates for instance_name feature

- content/documentation/staging/runtimes-monitoring/index.adoc
part of https://github.com/kiali/kiali/issues/4057
The netlify link that shows the new docs: https://deploy-preview-380--kiali.netlify.app/documentation/staging/runtimes-monitoring/
Here are all the PRs (including this one) that are related to this issue:
* https://github.com/kiali/kiali/pull/4059
* https://github.com/kiali/kiali-operator/pull/326
* https://github.com/kiali/helm-charts/pull/81
* https://github.com/kiali/kiali.io/pull/380
> consolidate dashboards

- content/documentation/staging/runtimes-monitoring/index.adoc
This was discussed here: https://github.com/kiali/kiali/issues/3555
netlify link: https://deploy-preview-385--kiali.netlify.app/documentation/staging/runtimes-monitoring/#_using_another_prometheus_instance
> show the two prom config settings together

- content/documentation/staging/installation-guide/index.adoc
- content/documentation/v1.36/installation-guide/index.adoc
Kiali 1.35 adds support for WorkloadGroup, which requires istio 1.8.
Fixes https://github.com/kiali/kiali/issues/4154
> Update compatibility chart.

- scripts/backports.py
- scripts/relnotes.py
For example, to list the backport PRs for v1.36 since patch release 1, searching the last 5 gihub projects:
`> python backports.py v1.36 1 5 <githubOauthToken>`
> Add script to figure out backports since the last release.

- content/documentation/staging/validations/index.adoc
Documentation changes related to https://github.com/kiali/kiali/pull/4256
> Added note about ignoring KIA0203 in case of subset not referenced in any Virtual Service.
